service: serveless-template
frameworkVersion: v1.0.1
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  environment:
    NODE_OPTIONS: '--enable-source-maps'
  versionFunctions: false
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: true
    websocket: true
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: '*'
package:
  individually: true
functions:
  hello: ${file(src/functions/hello/index.yml):hello}
resources:
  - ${file(src/resources/sns.yml)}
custom:
  stage: ${opt:stage, self:provider.stage}
  splitStacks:
    perFunction: true
    perType: false
  serverless-iam-roles-per-function:
    defaultInherit: true
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-plugin-split-stacks
