name: Deploy Project to Staging

# Deploy to staging on push to master branch.
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Dependabot auto-merge"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo Runs deployment
